blank_issues_enabled: true
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/vueform/builder/discussions/categories/questions
    about: Not sure about something? Start a "New discussion" and get an answer
  - name: ğŸ’¡ Feature Idea
    url: https://github.com/vueform/builder/discussions/categories/ideas
    about: Suggest a feature that will improve Vueform Builder by starting a "New discussion"
  - name: ğŸ“š Documentation
    url: https://builder.vueform.com/docs/saving
    about: Learning material for Vueform Builder
  - name: ğŸ’¬ Discussions
    url: https://github.com/vueform/builder/discussions
    about: Use discussions if you have another issue, an idea for improvement or for asking questions.